# Generated by Django 5.1.2 on 2024-11-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_orderitem_order'),
        ('Products', '0005_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.sizevariant'),
        ),
    ]
