# Generated by Django 5.1.2 on 2024-11-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_orderitem_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
    ]
