# Generated by Django 5.1.2 on 2024-11-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Order Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('requested_return', 'Requested Return'), ('approve_returned', 'Approve Returned'), ('reject_returned', 'Reject Returned')], default='pending', max_length=20),
        ),
    ]
