# Generated by Django 5.1.2 on 2024-11-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_order_payment_id_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
