# Generated by Django 5.1.2 on 2024-11-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Products', '0005_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='available_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.sizevariant'),
            preserve_default=False,
        ),
    ]
