# Generated by Django 5.1.2 on 2024-11-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cartitem_available_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='available_stock',
        ),
    ]
