# Generated by Django 5.1.2 on 2024-11-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
