# Generated by Django 5.1.2 on 2024-11-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_wallet_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
