# Generated by Django 5.1.2 on 2024-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
