# Generated by Django 5.1.2 on 2024-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_product_available_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
